### ISSUE TITLE
初使可行解

### ISSUE THREAD

**Issue by jiangshu-cn** [caidwang/alns_efsmtw_mt#2]
初使可行解是怎么生成的？

**Comment by caidwang** [comment]
初始可行解是根据最小费用增加的贪心算法增加一些random生成的

**Comment by jiangshu-cn** [comment]
> 初始可行解是根据最小费用增加的贪心算法增加一些random生成的

关于最小费用的贪心算法的代码在项目中我好像没有找到，是没有提交吗

**Comment by caidwang** [comment]
没有包括这部分王孙超Email: ***@***.***在 2023年2月2日，13:26，jiangshu-cn ***@***.***> 写道：﻿

初始可行解是根据最小费用增加的贪心算法增加一些random生成的

关于最小费用的贪心算法的代码在项目中我好像没有找到，是没有提交吗
